name: madura_store_mobile
description: Aplikasi mobile untuk MaduraStore e-commerce.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  cached_network_image: ^3.2.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
 